apiVersion: v1
kind: PersistentVolume
metadata:
  name: curtaurl-pv
  labels:
    app: curtaurl
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.hostPath.path }}
