apiVersion: v1
kind: Service
metadata:
  name: curtaurl
  labels:
    app: curtaurl
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4567
      protocol: TCP
  selector:
    app: curtaurl
